services:
  api:
    build:
      context: ./api
      dockerfile: /var/www/phishlab/docker/api/Dockerfile
    container_name: server_api
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      TZ: Europe/Paris
    volumes:
      - api_storage:/var/www/html/storage
      - api_cache:/var/www/html/bootstrap/cache
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: server_web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  db:
    image: mariadb:11
    container_name: server_db
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Europe/Paris
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  api_storage:
  api_cache:
